services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app_network

  mongodb:
    image: mongo:4.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app_network

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - app_network
    command: npm start

networks:
  app_network:
    driver: bridge
